dia = int(input("Dias: "))
horas = int(input("Horas: "))
minutos = int(input("Minutos: "))
segundos = int(input("Segundos: "))
print("Total de Tempo (em segundos): ",(dia*86400+horas*3600+minutos*60+segundos))
